parameters:
#    acme_my_api.example.class: Acme\MyApiBundle\Example

services:
#    acme_my_api.example:
#        class: %acme_my_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
